export {
  initTelemetry,
  shutdownTelemetry,
  withSpan,
  withFinancialSpan,
  currentTraceIds,
  addSpanAttributes,
  RastaSampler,
  ALWAYS_SAMPLE_ATTRIBUTE,
} from './telemetry';
export type { TelemetryConfig } from './telemetry';

export {
  registry,
  metricsText,
  metricsContentType,
  register,
  normalizeRoute,
  httpRequestDuration,
  httpRequestsTotal,
  httpActiveRequests,
  dbQueryDuration,
  dbPoolConnections,
  outboxPendingTotal,
  outboxPendingAgeSeconds,
  outboxAckFencedTotal,
  outboxLeaseReclaimedTotal,
  outboxClaimAttemptsTotal,
  outboxLeasesActive,
  eventsPublishedTotal,
  eventProcessingDuration,
  dlqMessagesTotal,
  eventValidationFailuresTotal,
  duplicateEventsTotal,
  authorizationDenialsTotal,
  authenticationFailuresTotal,
  Counter,
  Gauge,
  Histogram,
} from './metrics';
export type { Metric } from './metrics';
