import { Module, VersioningType, type INestApplication } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule, type OpenAPIObject } from '@nestjs/swagger';
import { spawnSync } from 'node:child_process';
import { z } from 'zod';
import { toJsonSchema } from './zod-schema';
import { NotificationController } from '../api/notification.controller';
import { NotificationApiService } from '../api/notification.service';
import {
  listNotificationsQuerySchema,
  notificationIdSchema,
  readAllQuerySchema,
} from '../api/notification.dto';
import {
  notificationPageSchema,
  notificationViewSchema,
  readAllResultSchema,
  unreadCountSchema,
} from '../api/notification.view';
import { PreferencesController } from '../preferences/preferences.controller';
import { PreferencesService } from '../preferences/preferences.service';
import {
  effectiveQuerySchema,
  preferenceInputSchema,
  replacePreferencesSchema,
} from '../preferences/preferences.dto';

/**
 * Fills in what Nest cannot see.
 *
 * Nest derives paths, methods and security from the decorators; it cannot see a
 * Zod schema, so the parameter and response shapes are added afterwards **from
 * the very schemas the service validates and serialises with**. One definition
 * rather than a decorated class beside a hand-written document that drift.
 *
 * ## The document is committed, and tested against the running service
 *
 * `docs/api/notification-service.openapi.json` is generated by
 * `pnpm --filter @rasta/notification-service openapi:generate` from
 * {@link buildDocumentationApp} — a module holding the controller and nothing
 * that needs a database — and committed, so a breaking change is visible in a
 * PR's diff (docs/api/README.md). `test/openapi.int-spec.ts` then builds the
 * same document from the **real** application, with its real guards, and
 * requires the two to be identical and every documented status reachable. A
 * committed document nothing compares is a second thing to keep in step; this
 * one has a comparator.
 *
 * The version stamped into the document is the package version, not
 * `SERVICE_VERSION` from the environment, so the generated file is the same
 * bytes on every machine.
 */

/** The package version, pinned so the committed document is deterministic. */
export const CONTRACT_VERSION = '0.1.0';

const apiErrorSchema = z
  .object({
    code: z.string(),
    message: z.string(),
    correlationId: z.string().optional(),
    details: z.array(z.unknown()).optional(),
  })
  .strict();

/**
 * The preference responses, described here rather than in a view file.
 *
 * The other endpoints serialise through `notification.view.ts`, which exists
 * because an in-app row has to be reshaped before it leaves. A preference does
 * not: what the service returns is what it stored, so a separate view would be
 * a file that only restated the schema. These two are the published shape.
 */
const preferenceListSchema = z.object({ preferences: z.array(preferenceInputSchema) }).strict();

const effectivePreferenceSchema = z
  .object({
    ruleKey: z.string(),
    channel: z.string(),
    enabled: z.boolean(),
    /** `MANDATORY_POLICY`, `RULE`, `CATEGORY`, `GLOBAL` or `CHANNEL_DEFAULT`. */
    decidedBy: z.string(),
    overridable: z.boolean(),
  })
  .strict();

/** Success responses, each with the status the handler actually answers. */
const RESPONSE_BODIES: Record<string, { status: '200'; schema: z.ZodTypeAny }> = {
  'GET /v1/notifications': { status: '200', schema: notificationPageSchema },
  'GET /v1/notifications/unread-count': { status: '200', schema: unreadCountSchema },
  'POST /v1/notifications/read-all': { status: '200', schema: readAllResultSchema },
  'GET /v1/notifications/{id}': { status: '200', schema: notificationViewSchema },
  'POST /v1/notifications/{id}/read': { status: '200', schema: notificationViewSchema },
  'POST /v1/notifications/{id}/dismiss': { status: '200', schema: notificationViewSchema },
  'GET /v1/preferences': { status: '200', schema: preferenceListSchema },
  'PUT /v1/preferences': { status: '200', schema: preferenceListSchema },
  'GET /v1/preferences/effective': { status: '200', schema: effectivePreferenceSchema },
};

const QUERY_SCHEMAS: Record<string, z.ZodTypeAny> = {
  'GET /v1/notifications': listNotificationsQuerySchema,
  'POST /v1/notifications/read-all': readAllQuerySchema,
  'GET /v1/preferences/effective': effectiveQuerySchema,
};

/** Request bodies, from the very schemas the pipe validates with. */
const REQUEST_BODIES: Record<string, z.ZodTypeAny> = {
  'PUT /v1/preferences': replacePreferencesSchema,
};

/** Paths whose `{id}` is validated by `notificationIdSchema`. */
const ID_PATHS = new Set([
  'GET /v1/notifications/{id}',
  'POST /v1/notifications/{id}/read',
  'POST /v1/notifications/{id}/dismiss',
]);

/**
 * The reachable error statuses, and only those.
 *
 * Each one is produced by a code path `test/openapi.int-spec.ts` exercises,
 * and that suite also asserts the converse: a documented status that nothing
 * can produce is removed rather than left standing.
 *
 * `409` and `422` are absent, for different reasons.
 *
 * Nothing here conflicts, so there is no `409` and there is no plan for one.
 *
 * `422` is the one worth explaining. NTF-003 implements the refusal ADR-054
 * § 5 calls for — turning off a channel a `MANDATORY` rule delivers on is
 * refused rather than stored and ignored — and `preferences.service.ts` throws
 * it, with unit tests in `precedence.spec.ts` holding the rule. It is not
 * documented because **no rule is `MANDATORY` today**: all three are `ROUTINE`,
 * so the deployed service cannot return it. Publishing a status a caller can
 * never receive is the same failure this whole design argues against — a
 * contract claiming a behaviour that does not exist. It is added the day the
 * first mandatory rule lands, with the `422` its integration test reaches.
 */
export const ERROR_DESCRIPTIONS: Record<number, string> = {
  400: 'The request does not match the published schema. `limit` is an integer from 1 to 200; an unknown query parameter is refused rather than ignored; an invalid, edited or unparseable `cursor` lands here too, as does an `id` that is not a prefixed ULID.',
  401: 'No credentials, or a token that is expired, unverifiable or issued for another audience.',
  403: 'Authenticated, but not permitted: a service-to-service token (no endpoint here grants one), or a user token that names no active organization.',
  404: 'Not found. Also returned for a notification that belongs to another person — in this organization or any other — or that has expired, so a row’s existence is never disclosed by the difference between two statuses. A preference naming a rule this service does not have lands here too: the shape was right, the thing named was not.',
  500: 'Unexpected server error.',
};

const DESCRIPTION =
  'The in-app inbox. Every endpoint returns or changes the authenticated user’s own ' +
  'notifications in the organization the request acts for, and nothing else: there is no ' +
  'administrative view of another person’s inbox, no way to name a tenant, and no DELETE — ' +
  'dismissing removes a row from the inbox and keeps it until retention. Reading is ' +
  'idempotent and monotonic; there is no un-read. Notifications are created by consuming ' +
  'domain events (INSURANCE_EXPIRING, INSPECTION_EXPIRING, MAINTENANCE_DUE) with semantic ' +
  'deduplication (ADR-054). Preferences decide who is told: a five-layer ladder — platform ' +
  'mandatory policy, then rule, category and global preferences, then the channel default — ' +
  'resolved per organization, so the same person can silence one tenant without silencing ' +
  'another. Email is delivered against a development mail server only: no production ' +
  'provider and no sender identity have been chosen (docs/24 Q-37), the shipped sender ' +
  'is an unresolvable .invalid address, and the readiness probe reports ' +
  'deliversToRealRecipients as false. Quiet hours defer an email into the end of the ' +
  'window rather than dropping it, and a CRITICAL notification ignores them.';

/** Builds the finished document for a booted application. */
export function buildNotificationOpenApiDocument(app: INestApplication): OpenAPIObject {
  const document = SwaggerModule.createDocument(
    app,
    new DocumentBuilder()
      .setTitle('Rasta — Notification Service')
      .setDescription(DESCRIPTION)
      .setVersion(CONTRACT_VERSION)
      .addBearerAuth()
      .build(),
  );

  return enrichOpenApiDocument(document);
}

/**
 * A module with the controller and an inert service — enough for Nest to
 * scan the routes, and nothing that opens a socket. Used by the generator
 * only; the integration test builds from the real `AppModule`.
 */
@Module({
  controllers: [NotificationController, PreferencesController],
  providers: [
    { provide: NotificationApiService, useValue: {} },
    { provide: PreferencesService, useValue: {} },
  ],
})
class DocumentationModule {}

export async function buildDocumentationApp(): Promise<INestApplication> {
  const app = await NestFactory.create(DocumentationModule, { logger: false });
  app.enableVersioning({ type: VersioningType.URI, defaultVersion: '1' });
  await app.init();
  return app;
}

export function enrichOpenApiDocument(document: OpenAPIObject): OpenAPIObject {
  document.components ??= {};
  document.components.schemas ??= {};
  document.components.schemas.ApiError = toJsonSchema(apiErrorSchema) as never;

  for (const [path, operations] of Object.entries(document.paths ?? {})) {
    for (const [method, operation] of Object.entries(operations)) {
      if (!isOperation(operation)) continue;

      const key = `${method.toUpperCase()} ${path}`;

      // Stated on the operation, not only in `components.securitySchemes`.
      // `addBearerAuth()` declares the scheme; it does not apply it, and
      // without this the contract would describe an inbox anybody can read.
      operation.security ??= [{ bearer: [] }];

      const query = QUERY_SCHEMAS[key];
      if (query) {
        operation.parameters = [...(operation.parameters ?? []), ...toQueryParameters(query)];
      }

      if (ID_PATHS.has(key)) {
        operation.parameters = (operation.parameters ?? []).map((parameter) =>
          isIdParameter(parameter)
            ? { ...parameter, required: true, schema: toJsonSchema(notificationIdSchema) }
            : parameter,
        );
      }

      const body = REQUEST_BODIES[key];
      if (body) {
        operation.requestBody = {
          required: true,
          content: { 'application/json': { schema: toJsonSchema(body) } },
        };
      }

      const response = RESPONSE_BODIES[key];
      if (response) {
        operation.responses ??= {};
        operation.responses[response.status] = {
          description: 'Success',
          content: { 'application/json': { schema: toJsonSchema(response.schema) } },
        };
        // Nest publishes a default `201` for every `@Post` and a default
        // `200` for every `@Get`; the handlers here all answer `200`.
        delete operation.responses['201'];
      }

      for (const [status, description] of Object.entries(ERROR_DESCRIPTIONS)) {
        operation.responses ??= {};
        operation.responses[status] ??= {
          description,
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ApiError' } },
          },
        };
      }
    }
  }

  return document;
}

interface MutableOperation {
  requestBody?: unknown;
  parameters?: unknown[];
  responses?: Record<string, unknown>;
  description?: string;
  security?: Record<string, string[]>[];
}

function isOperation(value: unknown): value is MutableOperation {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isIdParameter(value: unknown): value is { name: string; in: string } {
  return (
    typeof value === 'object' &&
    value !== null &&
    (value as { name?: unknown }).name === 'id' &&
    (value as { in?: unknown }).in === 'path'
  );
}

function toQueryParameters(schema: z.ZodTypeAny): unknown[] {
  const shape = objectShapeOf(schema);
  if (!shape) return [];

  return Object.entries(shape).map(([name, member]) => ({
    name,
    in: 'query',
    required: !member.isOptional(),
    schema: toJsonSchema(member),
  }));
}

function objectShapeOf(schema: z.ZodTypeAny): z.ZodRawShape | undefined {
  // JUSTIFIED-ANY: zod's `_def` is untyped across its type-kinds, and the walk
  // below re-checks the kind before reading a field.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let current: any = schema;

  for (let depth = 0; depth < 10; depth += 1) {
    const typeName = current?._def?.typeName;
    if (typeName === z.ZodFirstPartyTypeKind.ZodObject) {
      return (current as z.ZodObject<z.ZodRawShape>).shape;
    }
    if (typeName === z.ZodFirstPartyTypeKind.ZodEffects) {
      current = current._def.schema;
      continue;
    }
    if (
      typeName === z.ZodFirstPartyTypeKind.ZodOptional ||
      typeName === z.ZodFirstPartyTypeKind.ZodDefault
    ) {
      current = current._def.innerType;
      continue;
    }
    return undefined;
  }

  return undefined;
}

/**
 * The bytes the committed file holds: the document, formatted by the
 * repository's own Prettier configuration.
 *
 * `JSON.stringify(_, null, 2)` alone is not what `pnpm format:check` accepts —
 * Prettier collapses short arrays — and a generated file that the formatter
 * gate rewrites is a file two tools disagree about. The generator and both
 * comparators (`document.spec.ts`, `test/openapi.int-spec.ts`) go through this
 * one function, so all three agree on exactly one representation.
 */
export function formatDocument(document: OpenAPIObject, filePath: string): string {
  // The CLI rather than the library: Prettier 3's CommonJS entry loads its
  // implementation with a dynamic `import()`, which Jest's module sandbox
  // refuses without `--experimental-vm-modules`. A child process has no such
  // sandbox, and `--stdin-filepath` makes it resolve the repository config
  // exactly as `pnpm format:check` does for the committed file.
  const cli = require.resolve('prettier/bin/prettier.cjs');
  const result = spawnSync(
    process.execPath,
    [cli, '--parser', 'json', '--stdin-filepath', filePath],
    { input: JSON.stringify(document, null, 2), encoding: 'utf8' },
  );
  if (result.status !== 0) {
    throw new Error(`prettier failed to format the OpenAPI document: ${result.stderr}`);
  }
  return result.stdout;
}
